Traceback (most recent call last):
  File "/home/guilherme/repo/uniwallet/framework/Router.py", line 18, in route
    return self.resolve()
  File "/home/guilherme/repo/uniwallet/framework/Router.py", line 32, in resolve
    treater = self.call_controller(helper.get_package_from_module("controllers.treaters", "modules.{}".format(self.request.module)))
  File "/home/guilherme/repo/uniwallet/framework/Router.py", line 47, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/guilherme/repo/uniwallet/framework/Router.py", line 57, in instance_controller
    return controller.action(self.request.action)
  File "/home/guilherme/repo/uniwallet/framework/Controller.py", line 25, in action
    self.response.body = getattr(self, action_name)()
  File "/home/guilherme/repo/uniwallet/modules/backend/controllers/treaters/Auth.py", line 10, in login
    "method": "post"
  File "/home/guilherme/repo/uniwallet/framework/Treater.py", line 13, in rules
    return self.validate(rules)
  File "/home/guilherme/repo/uniwallet/framework/Treater.py", line 24, in validate
    response = rule_method(rules[rule_name])
  File "/home/guilherme/repo/uniwallet/framework/Treater.py", line 70, in rule_fields
    response = self.call_field_controller(field_rule, field_name.replace('[]', ''))
  File "/home/guilherme/repo/uniwallet/framework/Treater.py", line 94, in call_field_controller
    response = field_method(field_name, field_content, field_rule.split(':'))
  File "/home/guilherme/repo/uniwallet/framework/Treater.py", line 154, in field_exists
    connection = model.find({meta[1]: content})
  File "/home/guilherme/repo/uniwallet/framework/Model.py", line 115, in find
    return self.run_query(query, fields)
  File "/home/guilherme/repo/uniwallet/framework/Model.py", line 51, in run_query
    cursor = self.db.execute(query, data)
  File "/home/guilherme/repo/uniwallet/framework/Database.py", line 40, in execute
    cursor.execute(sql)
  File "/usr/lib/python3/dist-packages/mysql/connector/cursor.py", line 518, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/lib/python3/dist-packages/mysql/connector/connection.py", line 684, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/lib/python3/dist-packages/mysql/connector/connection.py", line 602, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1146 (42S02): Table 'Uniwallet.Companys' doesn't exist

