Traceback (most recent call last):
  File "/home/guilherme/repo/uniwallet/framework/Router.py", line 18, in route
    return self.resolve()
  File "/home/guilherme/repo/uniwallet/framework/Router.py", line 34, in resolve
    return self.call_controller(helper.get_package_from_module("controllers", "modules.{}".format(self.request.module)))
  File "/home/guilherme/repo/uniwallet/framework/Router.py", line 47, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/guilherme/repo/uniwallet/framework/Router.py", line 57, in instance_controller
    return controller.action(self.request.action)
  File "/home/guilherme/repo/uniwallet/framework/Controller.py", line 25, in action
    self.response.body = getattr(self, action_name)()
  File "/home/guilherme/repo/uniwallet/modules/backend/controllers/User.py", line 6, in register
    connection = self.model(self.get_request_parameters()).save()
  File "/home/guilherme/repo/uniwallet/framework/Controller.py", line 41, in model
    return self.model_class()(self.get_db_connection(), data)
  File "/home/guilherme/repo/uniwallet/framework/Model.py", line 9, in __init__
    self.define_attributes(data)
  File "/home/guilherme/repo/uniwallet/framework/Model.py", line 45, in define_attributes
    raise Exception("Error calling model '{}'. Attribute '{}' is missing on the passed data.".format(self.__class__.__name__, attr))
Exception: Error calling model 'User'. Attribute 'id' is missing on the passed data.

