api/product/register
Traceback (most recent call last):
  File "/home/moises/Documentos/uniwallet/framework/bootstrap.py", line 19, in bootstrap
    response = Application(request).run()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 15, in run
    return self.route()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 22, in route
    return self.resolve()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 35, in resolve
    return self.call_controller(general.get_package_from_module("controllers", "modules.{}".format(self.request.module)))
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 48, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 58, in instance_controller
    return controller.action(self.request.action)
  File "/home/moises/Documentos/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/moises/Documentos/uniwallet/modules/backend/controllers/Product.py", line 6, in register
    product_id = self.model(data = self.get_request_parameters()).save().last_id()
  File "/home/moises/Documentos/uniwallet/framework/Core.py", line 91, in model
    return self.get_class("models", self.__class__.__name__ if name is None else name)(request = self.request, data = data)
  File "/home/moises/Documentos/uniwallet/framework/Model.py", line 12, in __init__
    self.define_attributes(data)
  File "/home/moises/Documentos/uniwallet/framework/Model.py", line 54, in define_attributes
    raise Exception("Error calling model '{}'. Attribute '{}' is missing on the passed data.".format(self.__class__.__name__, attr))
Exception: Error calling model 'Product'. Attribute 'id' is missing on the passed data.

api/university/register
Traceback (most recent call last):
  File "/home/moises/Documentos/uniwallet/framework/bootstrap.py", line 19, in bootstrap
    response = Application(request).run()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 15, in run
    return self.route()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 22, in route
    return self.resolve()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 35, in resolve
    return self.call_controller(general.get_package_from_module("controllers", "modules.{}".format(self.request.module)))
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 48, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 58, in instance_controller
    return controller.action(self.request.action)
  File "/home/moises/Documentos/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/moises/Documentos/uniwallet/modules/backend/controllers/University.py", line 13, in register
    count = self.model(data = self.get_request_parameters()).save().count_rows()
  File "/home/moises/Documentos/uniwallet/framework/Model.py", line 81, in save
    connection = self.create()
  File "/home/moises/Documentos/uniwallet/framework/Model.py", line 112, in create
    return self.run_query(query)
  File "/home/moises/Documentos/uniwallet/framework/Model.py", line 70, in run_query
    cursor = self.db.execute(query, data)
  File "/home/moises/Documentos/uniwallet/framework/Database.py", line 40, in execute
    cursor.execute(sql)
  File "/usr/lib/python3/dist-packages/mysql/connector/cursor.py", line 552, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/lib/python3/dist-packages/mysql/connector/connection.py", line 490, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/lib/python3/dist-packages/mysql/connector/connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.DataError: 1406 (22001): Data too long for column 'name' at row 1

api/university/register
Traceback (most recent call last):
  File "/home/moises/Documentos/uniwallet/framework/bootstrap.py", line 19, in bootstrap
    response = Application(request).run()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 15, in run
    return self.route()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 22, in route
    return self.resolve()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 35, in resolve
    return self.call_controller(general.get_package_from_module("controllers", "modules.{}".format(self.request.module)))
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 48, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 58, in instance_controller
    return controller.action(self.request.action)
  File "/home/moises/Documentos/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/moises/Documentos/uniwallet/modules/backend/controllers/University.py", line 13, in register
    count = self.model(data = self.get_request_parameters()).save().count_rows()
  File "/home/moises/Documentos/uniwallet/framework/Core.py", line 91, in model
    return self.get_class("models", self.__class__.__name__ if name is None else name)(request = self.request, data = data)
  File "/home/moises/Documentos/uniwallet/framework/Model.py", line 12, in __init__
    self.define_attributes(data)
  File "/home/moises/Documentos/uniwallet/framework/Model.py", line 54, in define_attributes
    raise Exception("Error calling model '{}'. Attribute '{}' is missing on the passed data.".format(self.__class__.__name__, attr))
Exception: Error calling model 'University'. Attribute 'id' is missing on the passed data.

api/university/register
Traceback (most recent call last):
  File "/home/moises/Documentos/uniwallet/framework/bootstrap.py", line 19, in bootstrap
    response = Application(request).run()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 15, in run
    return self.route()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 22, in route
    return self.resolve()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 35, in resolve
    return self.call_controller(general.get_package_from_module("controllers", "modules.{}".format(self.request.module)))
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 48, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 58, in instance_controller
    return controller.action(self.request.action)
  File "/home/moises/Documentos/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/moises/Documentos/uniwallet/modules/backend/controllers/University.py", line 13, in register
    count = self.model(data = self.get_request_parameters()).save().count_rows()
  File "/home/moises/Documentos/uniwallet/framework/Core.py", line 91, in model
    return self.get_class("models", self.__class__.__name__ if name is None else name)(request = self.request, data = data)
  File "/home/moises/Documentos/uniwallet/framework/Model.py", line 12, in __init__
    self.define_attributes(data)
  File "/home/moises/Documentos/uniwallet/framework/Model.py", line 54, in define_attributes
    raise Exception("Error calling model '{}'. Attribute '{}' is missing on the passed data.".format(self.__class__.__name__, attr))
Exception: Error calling model 'University'. Attribute 'id' is missing on the passed data.

api/university/register
Traceback (most recent call last):
  File "/home/moises/Documentos/uniwallet/framework/bootstrap.py", line 19, in bootstrap
    response = Application(request).run()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 15, in run
    return self.route()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 22, in route
    return self.resolve()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 35, in resolve
    return self.call_controller(general.get_package_from_module("controllers", "modules.{}".format(self.request.module)))
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 48, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 58, in instance_controller
    return controller.action(self.request.action)
  File "/home/moises/Documentos/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/moises/Documentos/uniwallet/modules/backend/controllers/University.py", line 13, in register
    count = self.model(data = self.get_request_parameters()).save().count_rows()
  File "/home/moises/Documentos/uniwallet/framework/Core.py", line 91, in model
    return self.get_class("models", self.__class__.__name__ if name is None else name)(request = self.request, data = data)
  File "/home/moises/Documentos/uniwallet/framework/Model.py", line 12, in __init__
    self.define_attributes(data)
  File "/home/moises/Documentos/uniwallet/framework/Model.py", line 54, in define_attributes
    raise Exception("Error calling model '{}'. Attribute '{}' is missing on the passed data.".format(self.__class__.__name__, attr))
Exception: Error calling model 'University'. Attribute 'id' is missing on the passed data.

api/university/register
Traceback (most recent call last):
  File "/home/moises/Documentos/uniwallet/framework/bootstrap.py", line 19, in bootstrap
    response = Application(request).run()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 15, in run
    return self.route()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 22, in route
    return self.resolve()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 35, in resolve
    return self.call_controller(general.get_package_from_module("controllers", "modules.{}".format(self.request.module)))
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 48, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 58, in instance_controller
    return controller.action(self.request.action)
  File "/home/moises/Documentos/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/moises/Documentos/uniwallet/modules/backend/controllers/University.py", line 13, in register
    count = self.model(data = self.get_request_parameters()).save().count_rows()
  File "/home/moises/Documentos/uniwallet/framework/Core.py", line 91, in model
    return self.get_class("models", self.__class__.__name__ if name is None else name)(request = self.request, data = data)
  File "/home/moises/Documentos/uniwallet/framework/Model.py", line 12, in __init__
    self.define_attributes(data)
  File "/home/moises/Documentos/uniwallet/framework/Model.py", line 54, in define_attributes
    raise Exception("Error calling model '{}'. Attribute '{}' is missing on the passed data.".format(self.__class__.__name__, attr))
Exception: Error calling model 'University'. Attribute 'id' is missing on the passed data.

api/product/delete
Traceback (most recent call last):
  File "/home/moises/Documentos/uniwallet/framework/bootstrap.py", line 19, in bootstrap
    response = Application(request).run()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 15, in run
    return self.route()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 22, in route
    return self.resolve()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 33, in resolve
    treater = self.call_controller(general.get_package_from_module("controllers.treaters", "modules.{}".format(self.request.module)))
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 48, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 58, in instance_controller
    return controller.action(self.request.action)
  File "/home/moises/Documentos/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/moises/Documentos/uniwallet/framework/Treater.py", line 295, in delete
    "auth": ["god"]
  File "/home/moises/Documentos/uniwallet/framework/Treater.py", line 11, in rules
    return self.validate(rules)
  File "/home/moises/Documentos/uniwallet/framework/Treater.py", line 22, in validate
    response = rule_method(rules[rule_name])
  File "/home/moises/Documentos/uniwallet/framework/Treater.py", line 85, in rule_fields
    response = self.check_forbidden_fields(list(field.replace('[]', '') for field in fields.keys()), data_path)
  File "/home/moises/Documentos/uniwallet/framework/Treater.py", line 123, in check_forbidden_fields
    data = dictionary.access_nested_elem_from_list(self.get_request_parameters(), data_path)
  File "/home/moises/Documentos/uniwallet/framework/Core.py", line 30, in get_request_parameters
    for key, value in self.request.get_inputs_from_method().items():
AttributeError: 'int' object has no attribute 'items'

api/product/register
Traceback (most recent call last):
  File "/home/moises/Documentos/uniwallet/framework/bootstrap.py", line 19, in bootstrap
    response = Application(request).run()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 15, in run
    return self.route()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 22, in route
    return self.resolve()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 35, in resolve
    return self.call_controller(general.get_package_from_module("controllers", "modules.{}".format(self.request.module)))
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 48, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 58, in instance_controller
    return controller.action(self.request.action)
  File "/home/moises/Documentos/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/moises/Documentos/uniwallet/modules/backend/controllers/Product.py", line 6, in register
    product_id = self.model(data = self.get_request_parameters()).save().last_id()
  File "/home/moises/Documentos/uniwallet/framework/Core.py", line 91, in model
    return self.get_class("models", self.__class__.__name__ if name is None else name)(request = self.request, data = data)
  File "/home/moises/Documentos/uniwallet/framework/Model.py", line 12, in __init__
    self.define_attributes(data)
  File "/home/moises/Documentos/uniwallet/framework/Model.py", line 54, in define_attributes
    raise Exception("Error calling model '{}'. Attribute '{}' is missing on the passed data.".format(self.__class__.__name__, attr))
Exception: Error calling model 'Product'. Attribute 'id' is missing on the passed data.

api/product/register
Traceback (most recent call last):
  File "/home/moises/Documentos/uniwallet/framework/bootstrap.py", line 19, in bootstrap
    response = Application(request).run()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 15, in run
    return self.route()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 22, in route
    return self.resolve()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 35, in resolve
    return self.call_controller(general.get_package_from_module("controllers", "modules.{}".format(self.request.module)))
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 48, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 58, in instance_controller
    return controller.action(self.request.action)
  File "/home/moises/Documentos/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/moises/Documentos/uniwallet/modules/backend/controllers/Product.py", line 6, in register
    product_id = self.model(data = self.get_request_parameters()).save().last_id()
  File "/home/moises/Documentos/uniwallet/framework/Core.py", line 91, in model
    return self.get_class("models", self.__class__.__name__ if name is None else name)(request = self.request, data = data)
  File "/home/moises/Documentos/uniwallet/framework/Model.py", line 12, in __init__
    self.define_attributes(data)
  File "/home/moises/Documentos/uniwallet/framework/Model.py", line 54, in define_attributes
    raise Exception("Error calling model '{}'. Attribute '{}' is missing on the passed data.".format(self.__class__.__name__, attr))
Exception: Error calling model 'Product'. Attribute 'id' is missing on the passed data.

api/product/register
Traceback (most recent call last):
  File "/home/moises/Documentos/uniwallet/framework/bootstrap.py", line 19, in bootstrap
    response = Application(request).run()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 15, in run
    return self.route()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 22, in route
    return self.resolve()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 35, in resolve
    return self.call_controller(general.get_package_from_module("controllers", "modules.{}".format(self.request.module)))
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 48, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 58, in instance_controller
    return controller.action(self.request.action)
  File "/home/moises/Documentos/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/moises/Documentos/uniwallet/modules/backend/controllers/Product.py", line 6, in register
    product_id = self.model(data = self.get_request_parameters()).save().last_id()
  File "/home/moises/Documentos/uniwallet/framework/Core.py", line 91, in model
    return self.get_class("models", self.__class__.__name__ if name is None else name)(request = self.request, data = data)
  File "/home/moises/Documentos/uniwallet/framework/Model.py", line 12, in __init__
    self.define_attributes(data)
  File "/home/moises/Documentos/uniwallet/framework/Model.py", line 54, in define_attributes
    raise Exception("Error calling model '{}'. Attribute '{}' is missing on the passed data.".format(self.__class__.__name__, attr))
Exception: Error calling model 'Product'. Attribute 'id' is missing on the passed data.

api/product/register
Traceback (most recent call last):
  File "/home/moises/Documentos/uniwallet/framework/bootstrap.py", line 19, in bootstrap
    response = Application(request).run()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 15, in run
    return self.route()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 22, in route
    return self.resolve()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 35, in resolve
    return self.call_controller(general.get_package_from_module("controllers", "modules.{}".format(self.request.module)))
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 48, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 58, in instance_controller
    return controller.action(self.request.action)
  File "/home/moises/Documentos/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/moises/Documentos/uniwallet/modules/backend/controllers/Product.py", line 6, in register
    product_id = self.model(data = self.get_request_parameters()).save().last_id()
  File "/home/moises/Documentos/uniwallet/framework/Core.py", line 91, in model
    return self.get_class("models", self.__class__.__name__ if name is None else name)(request = self.request, data = data)
  File "/home/moises/Documentos/uniwallet/framework/Model.py", line 12, in __init__
    self.define_attributes(data)
  File "/home/moises/Documentos/uniwallet/framework/Model.py", line 54, in define_attributes
    raise Exception("Error calling model '{}'. Attribute '{}' is missing on the passed data.".format(self.__class__.__name__, attr))
Exception: Error calling model 'Product'. Attribute 'id' is missing on the passed data.

api/product/delete
Traceback (most recent call last):
  File "/home/moises/Documentos/uniwallet/framework/bootstrap.py", line 19, in bootstrap
    response = Application(request).run()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 15, in run
    return self.route()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 22, in route
    return self.resolve()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 33, in resolve
    treater = self.call_controller(general.get_package_from_module("controllers.treaters", "modules.{}".format(self.request.module)))
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 48, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 58, in instance_controller
    return controller.action(self.request.action)
  File "/home/moises/Documentos/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/moises/Documentos/uniwallet/framework/Treater.py", line 295, in delete
    "auth": ["god"]
  File "/home/moises/Documentos/uniwallet/framework/Treater.py", line 11, in rules
    return self.validate(rules)
  File "/home/moises/Documentos/uniwallet/framework/Treater.py", line 22, in validate
    response = rule_method(rules[rule_name])
  File "/home/moises/Documentos/uniwallet/framework/Treater.py", line 85, in rule_fields
    response = self.check_forbidden_fields(list(field.replace('[]', '') for field in fields.keys()), data_path)
  File "/home/moises/Documentos/uniwallet/framework/Treater.py", line 123, in check_forbidden_fields
    data = dictionary.access_nested_elem_from_list(self.get_request_parameters(), data_path)
  File "/home/moises/Documentos/uniwallet/framework/Core.py", line 30, in get_request_parameters
    for key, value in self.request.get_inputs_from_method().items():
AttributeError: 'int' object has no attribute 'items'

api/product/delete
Traceback (most recent call last):
  File "/home/moises/Documentos/uniwallet/framework/bootstrap.py", line 19, in bootstrap
    response = Application(request).run()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 15, in run
    return self.route()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 22, in route
    return self.resolve()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 33, in resolve
    treater = self.call_controller(general.get_package_from_module("controllers.treaters", "modules.{}".format(self.request.module)))
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 48, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 58, in instance_controller
    return controller.action(self.request.action)
  File "/home/moises/Documentos/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/moises/Documentos/uniwallet/framework/Treater.py", line 295, in delete
    "auth": ["god"]
  File "/home/moises/Documentos/uniwallet/framework/Treater.py", line 11, in rules
    return self.validate(rules)
  File "/home/moises/Documentos/uniwallet/framework/Treater.py", line 22, in validate
    response = rule_method(rules[rule_name])
  File "/home/moises/Documentos/uniwallet/framework/Treater.py", line 85, in rule_fields
    response = self.check_forbidden_fields(list(field.replace('[]', '') for field in fields.keys()), data_path)
  File "/home/moises/Documentos/uniwallet/framework/Treater.py", line 123, in check_forbidden_fields
    data = dictionary.access_nested_elem_from_list(self.get_request_parameters(), data_path)
  File "/home/moises/Documentos/uniwallet/framework/Core.py", line 30, in get_request_parameters
    for key, value in self.request.get_inputs_from_method().items():
AttributeError: 'int' object has no attribute 'items'

api/product/delete
Traceback (most recent call last):
  File "/home/moises/Documentos/uniwallet/framework/bootstrap.py", line 19, in bootstrap
    response = Application(request).run()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 15, in run
    return self.route()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 22, in route
    return self.resolve()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 33, in resolve
    treater = self.call_controller(general.get_package_from_module("controllers.treaters", "modules.{}".format(self.request.module)))
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 48, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 58, in instance_controller
    return controller.action(self.request.action)
  File "/home/moises/Documentos/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/moises/Documentos/uniwallet/framework/Treater.py", line 295, in delete
    "auth": ["god"]
  File "/home/moises/Documentos/uniwallet/framework/Treater.py", line 11, in rules
    return self.validate(rules)
  File "/home/moises/Documentos/uniwallet/framework/Treater.py", line 22, in validate
    response = rule_method(rules[rule_name])
  File "/home/moises/Documentos/uniwallet/framework/Treater.py", line 85, in rule_fields
    response = self.check_forbidden_fields(list(field.replace('[]', '') for field in fields.keys()), data_path)
  File "/home/moises/Documentos/uniwallet/framework/Treater.py", line 123, in check_forbidden_fields
    data = dictionary.access_nested_elem_from_list(self.get_request_parameters(), data_path)
  File "/home/moises/Documentos/uniwallet/framework/Core.py", line 30, in get_request_parameters
    for key, value in self.request.get_inputs_from_method().items():
AttributeError: 'int' object has no attribute 'items'

api/product/delete
Traceback (most recent call last):
  File "/home/moises/Documentos/uniwallet/framework/bootstrap.py", line 19, in bootstrap
    response = Application(request).run()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 15, in run
    return self.route()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 22, in route
    return self.resolve()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 33, in resolve
    treater = self.call_controller(general.get_package_from_module("controllers.treaters", "modules.{}".format(self.request.module)))
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 48, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 58, in instance_controller
    return controller.action(self.request.action)
  File "/home/moises/Documentos/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/moises/Documentos/uniwallet/framework/Treater.py", line 295, in delete
    "auth": ["god"]
  File "/home/moises/Documentos/uniwallet/framework/Treater.py", line 11, in rules
    return self.validate(rules)
  File "/home/moises/Documentos/uniwallet/framework/Treater.py", line 22, in validate
    response = rule_method(rules[rule_name])
  File "/home/moises/Documentos/uniwallet/framework/Treater.py", line 85, in rule_fields
    response = self.check_forbidden_fields(list(field.replace('[]', '') for field in fields.keys()), data_path)
  File "/home/moises/Documentos/uniwallet/framework/Treater.py", line 123, in check_forbidden_fields
    data = dictionary.access_nested_elem_from_list(self.get_request_parameters(), data_path)
  File "/home/moises/Documentos/uniwallet/framework/Core.py", line 30, in get_request_parameters
    for key, value in self.request.get_inputs_from_method().items():
AttributeError: 'list' object has no attribute 'items'

api/wallet/balance
Traceback (most recent call last):
  File "/home/moises/Documentos/uniwallet/framework/bootstrap.py", line 19, in bootstrap
    response = Application(request).run()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 15, in run
    return self.route()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 22, in route
    return self.resolve()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 35, in resolve
    return self.call_controller(general.get_package_from_module("controllers", "modules.{}".format(self.request.module)))
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 48, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 58, in instance_controller
    return controller.action(self.request.action)
  File "/home/moises/Documentos/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/moises/Documentos/uniwallet/modules/backend/controllers/Wallet.py", line 20, in balance
    user_id = self.model(name = 'Session').get_user()['id']
TypeError: 'NoneType' object is not subscriptable

api/wallet/balance
Traceback (most recent call last):
  File "/home/moises/Documentos/uniwallet/framework/bootstrap.py", line 19, in bootstrap
    response = Application(request).run()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 15, in run
    return self.route()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 22, in route
    return self.resolve()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 35, in resolve
    return self.call_controller(general.get_package_from_module("controllers", "modules.{}".format(self.request.module)))
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 48, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 58, in instance_controller
    return controller.action(self.request.action)
  File "/home/moises/Documentos/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/moises/Documentos/uniwallet/modules/backend/controllers/Wallet.py", line 20, in balance
    user_id = self.model(name = 'Session').get_user()['id']
TypeError: 'NoneType' object is not subscriptable

api/consumer/extrato
Traceback (most recent call last):
  File "/home/moises/Documentos/uniwallet/framework/bootstrap.py", line 19, in bootstrap
    response = Application(request).run()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 15, in run
    return self.route()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 22, in route
    return self.resolve()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 35, in resolve
    return self.call_controller(general.get_package_from_module("controllers", "modules.{}".format(self.request.module)))
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 48, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 58, in instance_controller
    return controller.action(self.request.action)
  File "/home/moises/Documentos/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/moises/Documentos/uniwallet/modules/backend/controllers/Consumer.py", line 35, in extrato
    user_id = self.model(name = 'Session').get_user()['id']
TypeError: 'NoneType' object is not subscriptable

api/wallet/balance
Traceback (most recent call last):
  File "/home/moises/Documentos/uniwallet/framework/bootstrap.py", line 19, in bootstrap
    response = Application(request).run()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 15, in run
    return self.route()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 22, in route
    return self.resolve()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 35, in resolve
    return self.call_controller(general.get_package_from_module("controllers", "modules.{}".format(self.request.module)))
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 48, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 58, in instance_controller
    return controller.action(self.request.action)
  File "/home/moises/Documentos/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/moises/Documentos/uniwallet/modules/backend/controllers/Wallet.py", line 20, in balance
    user_id = self.model(name = 'Session').get_user()['id']
TypeError: 'NoneType' object is not subscriptable

api/product/delete
Traceback (most recent call last):
  File "/home/moises/Documentos/uniwallet/framework/bootstrap.py", line 19, in bootstrap
    response = Application(request).run()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 15, in run
    return self.route()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 22, in route
    return self.resolve()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 35, in resolve
    return self.call_controller(general.get_package_from_module("controllers", "modules.{}".format(self.request.module)))
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 48, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 58, in instance_controller
    return controller.action(self.request.action)
  File "/home/moises/Documentos/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/moises/Documentos/uniwallet/framework/Controller.py", line 57, in delete
    return "Done: {} rows affected".format(self.model().destroy(list(('id', '=', item['id']) for item in self.get_input('data'))).count_rows())
  File "/home/moises/Documentos/uniwallet/framework/Model.py", line 122, in destroy
    return self.run_query(query.get())
  File "/home/moises/Documentos/uniwallet/framework/Model.py", line 70, in run_query
    cursor = self.db.execute(query, data)
  File "/home/moises/Documentos/uniwallet/framework/Database.py", line 40, in execute
    cursor.execute(sql)
  File "/usr/lib/python3/dist-packages/mysql/connector/cursor.py", line 552, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/lib/python3/dist-packages/mysql/connector/connection.py", line 490, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/lib/python3/dist-packages/mysql/connector/connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.IntegrityError: 1451 (23000): Cannot delete or update a parent row: a foreign key constraint fails (`Uniwallet`.`Purchase_Product`, CONSTRAINT `Purchase_Product_ibfk_2` FOREIGN KEY (`product_id`) REFERENCES `Products` (`id`))

api/store/fetchadmin
Traceback (most recent call last):
  File "/home/moises/Documentos/uniwallet/framework/Core.py", line 71, in get_class
    return getattr(importlib.import_module("modules.{}.{}.{}".format(self.request.module, module_dir, class_name)), class_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'modules.backend.models.Store'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/moises/Documentos/uniwallet/framework/bootstrap.py", line 19, in bootstrap
    response = Application(request).run()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 15, in run
    return self.route()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 22, in route
    return self.resolve()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 35, in resolve
    return self.call_controller(general.get_package_from_module("controllers", "modules.{}".format(self.request.module)))
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 48, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 58, in instance_controller
    return controller.action(self.request.action)
  File "/home/moises/Documentos/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/moises/Documentos/uniwallet/modules/backend/controllers/Store.py", line 14, in fetchadmin
    return (self.model().find(join=[('Company', 'company_id')], start_from = self.get_input('start'), limit = self.get_input('limit'))
  File "/home/moises/Documentos/uniwallet/framework/Core.py", line 91, in model
    return self.get_class("models", self.__class__.__name__ if name is None else name)(request = self.request, data = data)
  File "/home/moises/Documentos/uniwallet/framework/Core.py", line 73, in get_class
    raise Exception("Error invoking class '{}': {}".format(class_name, str(e)))
Exception: Error invoking class 'Store': No module named 'modules.backend.models.Store'

api/product/delete
Traceback (most recent call last):
  File "/home/moises/Documentos/uniwallet/framework/bootstrap.py", line 19, in bootstrap
    response = Application(request).run()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 15, in run
    return self.route()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 22, in route
    return self.resolve()
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 35, in resolve
    return self.call_controller(general.get_package_from_module("controllers", "modules.{}".format(self.request.module)))
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 48, in call_controller
    return self.instance_controller(package, controller_name)
  File "/home/moises/Documentos/uniwallet/framework/Application.py", line 58, in instance_controller
    return controller.action(self.request.action)
  File "/home/moises/Documentos/uniwallet/framework/Controller.py", line 18, in action
    self.response.body = getattr(self, action_name)()
  File "/home/moises/Documentos/uniwallet/framework/Controller.py", line 57, in delete
    return "Done: {} rows affected".format(self.model().destroy(list(('id', '=', item['id']) for item in self.get_input('data'))).count_rows())
  File "/home/moises/Documentos/uniwallet/framework/Model.py", line 122, in destroy
    return self.run_query(query.get())
  File "/home/moises/Documentos/uniwallet/framework/Model.py", line 70, in run_query
    cursor = self.db.execute(query, data)
  File "/home/moises/Documentos/uniwallet/framework/Database.py", line 40, in execute
    cursor.execute(sql)
  File "/usr/lib/python3/dist-packages/mysql/connector/cursor.py", line 552, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/lib/python3/dist-packages/mysql/connector/connection.py", line 490, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/lib/python3/dist-packages/mysql/connector/connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.IntegrityError: 1451 (23000): Cannot delete or update a parent row: a foreign key constraint fails (`Uniwallet`.`Product_Prices`, CONSTRAINT `Product_Prices_ibfk_1` FOREIGN KEY (`product_id`) REFERENCES `Products` (`id`))

